# Generated by Django 5.2.1 on 2025-05-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedPrice',
            fields=[
                ('calculated_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('calculated_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_repository.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_repository.product')),
            ],
        ),
    ]
