# Generated by Django 5.2.1 on 2025-05-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_calculated_price_order_prices'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatedPrice',
        ),
    ]
