# Generated by Django 5.2.1 on 2025-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('DRINK', 'Drink'), ('FOOD', 'Food'), ('SET', 'Set'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
            ],
        ),
    ]
