# Generated by Django 5.2.1 on 2025-05-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('product_repository', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_price', models.FloatField()),
                ('distance', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PREPARED', 'Prepared'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURNED', 'Returned')], default='CREATED', max_length=15)),
                ('calculated_price', models.ManyToManyField(to='pricing.calculatedprice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('products', models.ManyToManyField(to='product_repository.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
    ]
