# Generated by Django 5.2.1 on 2025-05-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='calculated_price',
        ),
        migrations.AddField(
            model_name='order',
            name='prices',
            field=models.ManyToManyField(to='pricing.price'),
        ),
    ]
